name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: team_xUTrvMl3476cPd2dBrn7fXyP
      VERCEL_PROJECT_ID: prj_4lnLNjnto5HkqBWJcpaMu2YSMDZ5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (build on Vercel servers)
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
